---
title: "Machine Learning Code_FinalProj"
author: "Annika Balk, Chloe Singer, Jon Niemann, You Been Park"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Beginning Stages of Code
Commit your updates to the repo when you can

```{r}
library(tidyverse)

extract_upper_triangle <- function(mat) {
  mat[upper.tri(mat)]
}

process_connectomes <- function(folder_path) {
  tsv_files <- list.files(folder_path, pattern = "\\.tsv$", full.names = TRUE) %>%
    unique()
  
  data <- tsv_files %>%
    set_names(~ tools::file_path_sans_ext(basename(.))) %>%
    map_df(~ {
      mat <- as.matrix(read_tsv(.x, col_names = FALSE, show_col_types = FALSE))
      tibble(id = tools::file_path_sans_ext(basename(.x)),
             features = list(extract_upper_triangle(mat)))
    })

  # DEBUG: Check if `features` column exists
  print(names(data))
  print(head(data))

  # Fix: unnest the list-column
  data_features <- data %>%
    unnest_wider(features, names_sep = "_")

  return(data_features)
}

# Run for training and test sets
train_path <- "~/Desktop/Mystery/Mysteries-of-Female-Brain-Project/data/train_tsv/train_tsv"
test_path <- "~/Desktop/Mystery/Mysteries-of-Female-Brain-Project/data/test_tsv/test_tsv"

list.files(train_path)
list.files(test_path)

train_df  <- process_connectomes(train_path)
test_df  <- process_connectomes(test_path)

train_metadata <- read_csv("~/Desktop/Mystery/Mysteries-of-Female-Brain-Project/data/metadata/training_metadata.csv")
test_metadata <- read_csv("~/Desktop/Mystery/Mysteries-of-Female-Brain-Project/data/metadata/test_metadata.csv")

# Join metadata to feature vectors
train_final <- left_join(train_metadata, train_df, by = c("participant_id" = "id"))
test_final  <- left_join(test_metadata,  test_df,  by = c("participant_id" = "id"))

```
